---
# tasks file for prep-rundeck-target.yml

- name: Comment out password sudo for wheel group
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "%wheel ALL=(ALL)       ALL"
    line: "#%wheel ALL=(ALL)       ALL"
    backrefs: yes
    state: present

- name: Uncomment passwordless sudo for wheel group
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "#%wheel  ALL=(ALL)       NOPASSWD: ALL"
    line: "%wheel  ALL=(ALL)       NOPASSWD: ALL"
    backrefs: yes
    state: present

- name: Ensure rundeck user
  become: true
  ansible.builtin.user:
    name: rundeck
    uid: 1002
    shell: /bin/bash
    groups: rundeck,wheel
    state: present

- name: Ensure rundeck user ssh dir
  become: true
  ansible.builtin.file:
    path: /home/rundeck/.ssh
    state: directory
    owner: rundeck
    group: rundeck
    mode: '700'

- name: Get rundeck public key
  become: true
  ansible.builtin.command:
    cmd: cat /var/lib/rundeck/.ssh/id_rsa.pub
  register: rundeck_pub_key
  delegate_to: rundeck
  changed_when: False

- name: Ensure rundeck public key in authorized_keys
  become: true
  ansible.builtin.lineinfile:
    path: /home/rundeck/.ssh/authorized_keys
    backrefs: yes
    create: yes
    owner: rundeck
    group: rundeck
    mode: '600'
    regexp: "{{ rundeck_pub_key.stdout }}"
    line: "{{ rundeck_pub_key.stdout }}"
    state: present   

