---
# defaults file for rundeck-community-testing

rundeck_java_pkg: "java-11-openjdk.x86_64"

rundeck_http_port: 4440
rundeck_http_port_state: enabled

rundeck_https_port: 4443
rundeck_https_port_state: enabled
